# Generated by Django 4.2 on 2023-04-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_renting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='renting_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='returning_date',
        ),
    ]
