# Generated by Django 4.2 on 2023-04-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_renting', '0002_remove_book_renting_date_remove_book_returning_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renting_date', models.DateField()),
                ('due_date', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('renting_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookss', to='book_renting.book')),
            ],
        ),
    ]
