# Generated by Django 4.2 on 2023-04-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_renting', '0003_renting'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='renting_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='renting',
            name='renting_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_books', to='book_renting.book'),
        ),
    ]
